---
title: "SALAD analyses of cortisol data"
author: "Lara Wieland"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
fig_caption: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aggregated Data Import
```{r}
## NECESSARY TO RUN THIS FIRST
source('preps/data_import.R')

```
# Aggregated Data Prep
```{r, include=FALSE}
## NECESSARY TO RUN THIS FIRST
source('preps/prep_agg.R')

```
# Cortisol Data Prep
```{r, include=FALSE}
## NECESSARY TO RUN THIS FIRST
source('preps/cort_import.R')

```

## Single Trial Analyses Prep
```{r}
## NECESSARY TO RUN THIS FIRST
source("preps/import_singletrial_data.R")
```

# Cortisol and Behavioral Aggregation 
```{r, include=FALSE}

## NECESSARY TO RUN THIS FIRST
source('preps/prep_cortbehav.R')

```

## Sanity check 1: Check distribution of cortisol and amylase
```{r, echo=FALSE}

# create basic histograms to check distribution of cortisol

data_physio_clean.HC <- data_physio_clean %>% filter(Gruppe == "Control")

hist(data_physio_clean$t1_cort)
hist(data_physio_clean$t2_cort)
hist(data_physio_clean$t3_cort)
hist(data_physio_clean$t4_cort)
hist(data_physio_clean$t5_cort)
hist(data_physio_clean$t6_cort)

hist(data_physio_clean$peak_cort)
hist(data_physio_clean$aucg)
hist(data_physio_clean$aucg_amyl)

hist(data_physio_clean$t1_amyl)
hist(data_physio_clean$t2_amyl)
hist(data_physio_clean$t3_amyl)
hist(data_physio_clean$t4_amyl)
hist(data_physio_clean$t5_amyl)
hist(data_physio_clean$t6_amyl)

hist(data_physio_clean$peak_amyl)


#names(data_physio_behav_1) = gsub(pattern = "_3*", replacement = "", x = names(data_physio_behav_1))

# "t1_cort_control","t2_cort_control","t3_cort_control","t4_cort_control","t5_cort_control","t6_cort_control","t1_amyl_control","t2_amyl_control","t3_amyl_control","t4_amyl_control","t5_amyl_control","t6_amyl_control","peak_cort_control","z.peak_cort_control","t1_cort_stress","t2_cort_stress","t3_cort_stress","t4_cort_stress","t5_cort_stress","t6_cort_stress","t1_amyl_stress","t2_amyl_stress","t3_amyl_stress","t4_amyl_stress","t5_amyl_stress","t6_amyl_stress","peak_cort_stress","z.peak_cort_stress","p_correct_CT","p_stay_CT","p_switch_CT","p_win_stay_CT","p_win_switch_CT","p_lose_stay_CT","p_lose_switch_CT","mean_RT_ST","p_correct_ST","p_stay_ST","p_switch_ST","p_win_stay_ST","p_win_switch_ST","p_lose_stay_ST","p_lose_switch_ST",

# ADAPT HERE
data_physio_long.HC <- data_physio_long %>%  filter(Gruppe == "Control", marker == "amyl")
#data_physio_long.HC <- data_physio_long %>%  filter(Gruppe == "Control", marker == "cort")

# Claudia's function se that calculates the standard errors
se <- function(x) sd(x, na.rm=TRUE)/sqrt(length(x)-sum(is.nan(x)))

time_means <- data_physio_long.HC %>%
    group_by(variable_name,time,condition) %>%
    summarize(Mean = mean(value, na.rm = TRUE),SE = se(value)) %>% data.frame()

# TSST effect
tsst_plot <- 
  ggplot(time_means, aes(x=time,y=Mean, color = condition)) + geom_point() + geom_line() +      
  geom_errorbar(aes(ymin=Mean-SE, ymax=Mean+SE),width=.2) +
  scale_color_manual(values = c("#00BFC4", "#F8766D")) +
  scale_x_continuous(breaks=c(1,2,3,4,5,6), labels=c("T1 (-30)", "T2 (-2)", "T3 (+10)","T4 (+15)","T5 (+30)","T6 (45)"), limits=c(0.5, 7)) +
  #scale_y_continuous(limits=c(0,11)) +
  scale_y_continuous(limits=c(100,350)) +
  # annotate("rect", xmin = 2.2, xmax = 3, ymin = 0, ymax = 11, fill="turquoise", alpha = .2) +
  # annotate("rect", xmin = 4, xmax = 5, ymin = 0, ymax = 11, fill="darkgrey", alpha = .2) +
  annotate("rect", xmin = 2.2, xmax = 3, ymin = 100, ymax = 350, fill="turquoise", alpha = .2) +
  annotate("rect", xmin = 4, xmax = 5, ymin = 100, ymax = 350, fill="darkgrey", alpha = .2) +
   xlab("Time Point") + ylab("Amylase activity in saliva in U/ml") +
   labs(title = 'Alpha-amylase stress response over the course of experimental session',
        subtitle = 'Clear effect of stress condition',
        col = "Condition") + 
   theme(plot.title = element_text(face = "italic"))
   theme_classic()
   
tsst_plot

# paired ttest for AUC ST vs. CT: significant difference
auc.cort.ttest <- stats::t.test(data_physio_behav_red$aucg_control, data_physio_behav_red$aucg_stress, paired = TRUE)
auc.amyl.ttest <- stats::t.test(data_physio_behav_red$aucg_amyl_control, data_physio_behav_red$aucg_amyl_stress, paired = TRUE)

# paired ttest for pre-stress cortisol between ST and CT: no significant difference
auc.T1cort.ttest <- stats::t.test(dat_physio_behav$t1_cort_control, dat_physio_behav$t1_cort_stress, paired = TRUE)
```


## Sanity check 2: Check cortisol-responder
```{r, echo=FALSE}
# Lennart's paper: Of the 34 participants, 6 (18%) showed a cortisol response of < 1.5 nmol/l (Miller et al., 2013) and were therefore considered non-responders. 
# Should we do this as well (and if so with T4-T2, there is no info on the time points in Lennart's paper) or no need with our analysis approach of AUC?
# in our study: that would be 4 participants but how to go on then? Lennart did all behavioral analyses separately with responders but had a larger sample to start with

dat_physio_behav <- dat_physio_behav %>% rowwise() %>% mutate(cort_response_stress=t4_cort_stress-t2_cort_stress)

cort.nonresponder <- dat_physio_behav %>% filter(cort_response_stress < 1.5)

```


## Cortisol+Behav Analyses Plots
```{r}

# calculate the difference between individual values (ST-CT) for single phases and all
data_physio_behav_red <- mutate(data_physio_behav_red, diff_STCT_pre = p_correct_pre_ST - p_correct_pre_CT)
data_physio_behav_red <- mutate(data_physio_behav_red,m_diff_STCT_pre = mean(diff_STCT_pre))

data_physio_behav_red <- mutate(data_physio_behav_red, diff_STCT_rev = p_correct_rev_ST - p_correct_rev_CT)
data_physio_behav_red <- mutate(data_physio_behav_red,m_diff_STCT_rev = mean(diff_STCT_rev))

data_physio_behav_red <- mutate(data_physio_behav_red, diff_STCT_post = p_correct_post_ST - p_correct_post_CT)
data_physio_behav_red <- mutate(data_physio_behav_red,m_diff_STCT_post = mean(diff_STCT_post))

data_physio_behav_red <- mutate(data_physio_behav_red, diff_STCT = p_correct_ST - p_correct_CT)

# create continuous variable for interindividual cortisol response change:
data_physio_behav_red <- data_physio_behav_red %>% rowwise() %>% mutate(aucg_diff = aucg_stress - aucg_control)

plot.interindiv.cort <- ggplot(data_physio_behav_red, aes(x=group, y=aucg_diff, color = order)) + 
  geom_boxplot(outlier.shape=NA) + #avoid plotting outliers twice
  geom_jitter(position=position_jitter(width=.1, height=0)) +
   xlab("Group") + ylab("Differences between ST and CT AUCG Cortisol") 

plot.diff.corr <- ggscatter(data_physio_behav_red, x = "diff_STCT", y = "aucg_diff", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Interindiv p_correct differences", ylab = "Interindiv AUC-G cortisol differences")
plot.diff.corr

dat_physio_behav.HC <- dat_physio_behav %>%
filter(Gruppe_control=="Control")

# two separate plots: 1) y= p_correct_ST x = z_peak_cort_ST 2) y = p_correct_CT x = z_peak_cort_CT
# all in one plot: y= p_correct, z = z_peak_cort, color= condition
#dat_physio_behav_2 <- dat_physio_behav_1 %>% drop_na(peak_cort_control)

# in whole sample
physio_plot1 <- ggscatter(dat_physio_behav, x = "p_correct_ST", y = "z.peak_cort_stress", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Correct Responses (ST)", ylab = "Cortisol Peak (ST)")
physio_plot1

# only HC
physio_plot2 <-  ggscatter(dat_physio_behav.HC, x = "p_correct_ST", y = "z.peak_cort_stress", na.rm = TRUE,
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Correct Responses (ST)", ylab = "Cortisol Peak (CT)")
physio_plot2

physio_plot3 <-  ggscatter(dat_physio_behav.HC, x = "p_correct_ST", y = "aucg_stress", na.rm = TRUE,
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Correct Responses (ST)", ylab = "AUC Cortisol (ST)")
physio_plot3

physio_plot4 <-  ggscatter(dat_physio_behav.HC, x = "p_win_stay_ST", y = "aucg_stress", na.rm = TRUE,
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Win Stay Behavior (ST)", ylab = "AUC Cortisol (ST)")
physio_plot4

physio_plot5 <-  ggscatter(dat_physio_behav.HC, x = "p_lose_switch_ST", y = "aucg_stress", na.rm = TRUE,
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Lose Switch Behavior (ST)", ylab = "AUC Cortisol (ST)")
physio_plot5

```


## Exploratory Analyses: WM-Median Split - Cortisol - Performance (inspired by Otto,2013)
```{r}

# dichotomize HC dataset by WM capacity (num_backward)
dat_physio_behav$wm_cap <- dicho(dat_physio_behav$num_backward, dich.by = "median", as.num = TRUE)
dat_physio_behav$wm_cap <-factor(dat_physio_behav$wm_cap, labels=c("low WM", "high WM"))

# transform dat_physio_behav into half long format (by condition)
# first for aucg variable
longdat.cond.phys <- melt(dat_physio_behav,
        # ID variables - all the variables to keep but not split apart on
    id.vars=c("sub_id","wm_cap"),
        # The source columns
    measure.vars=c("aucg_control","aucg_stress"),
        # Name of the destination column that will identify the original
        # column that the measurement came from
    variable.name="cond",
    value.name="aucg"
)

# then for z.peak_cort variable
longdat.cond.phys2 <- melt(dat_physio_behav,
        # ID variables - all the variables to keep but not split apart on
    id.vars=c("sub_id","wm_cap"),
        # The source columns
    measure.vars=c("z.peak_cort_control","z.peak_cort_stress"),
        # Name of the destination column that will identify the original
        # column that the measurement came from
    variable.name="cond",
    value.name="z.peak"
)

# transform data_all into half long format (by condition)
longdat.cond.correct <- melt(data_all,
                        # ID variables - all the variables to keep but not split apart on
                        id.vars=c("sub_id","al_win", "al_loss", "kappa", "beta_win","beta_loss"),
                        # The source columns
                        measure.vars=c("p_correct_ST","p_correct_CT"),
                        # Name of the destination column that will identify the original
                        # column that the measurement came from
                        variable.name="cond",
                        value.name="p_correct"
)

# extract string ST or CT from phase strings and turn it into logical, then numeric
longdat.cond.correct <- longdat.cond.correct %>% mutate(cond = grepl("*CT",longdat.cond.correct$cond)) 
longdat.cond.correct <- longdat.cond.correct %>% mutate(cond2 = longdat.cond.correct$cond*1)
longdat.cond.correct$cond2<-factor(longdat.cond.correct$cond2, labels=c("stress", "control"))

library(plyr)

# the following steps prepare both longdats (either longdat.cond.phys = aucg or longdat.cond.phys2 = zpeak) for the merge with longdat.cond.correct
longdat.cond.phys$cond2 <- revalue(longdat.cond.phys$cond, c("aucg_control" = "control","aucg_stress"="stress"))
longdat.cond.phys2$cond2 <- revalue(longdat.cond.phys2$cond, c("z.peak_cort_control" = "control","z.peak_cort_stress"="stress"))

longdat.cond.phys$sub_id <- factor(longdat.cond.phys$sub_id)
longdat.cond.phys2$sub_id <- factor(longdat.cond.phys2$sub_id)

longdat.cond.correct$sub_id <- factor(longdat.cond.correct$sub_id)

longdat.cond.both <- merge.data.frame(longdat.cond.phys,longdat.cond.correct, by = c("sub_id", "cond2"))
longdat.cond.both2 <- merge.data.frame(longdat.cond.phys2,longdat.cond.correct, by = c("sub_id", "cond2"))

# plots correct performance onto cortisol stress level in both conditions
wm_plot <- 
  ggplot(longdat.cond.both, aes(aucg,p_correct, color = wm_cap)) + geom_point() + geom_smooth(aes(group = wm_cap), method = "lm", se = FALSE) + facet_wrap(~cond2)
wm_plot

# like Otto Fig 4, low and high WM span subjects separate for p_correct
wm_plot_1 <- ggscatter(longdat.cond.both, x = "aucg", y = "p_correct", color = "cond2",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "AUC (Cortisol Stress Response)", ylab = "Percentage of correct responses") + facet_wrap("wm_cap")
wm_plot_1

wm_plot_2 <- ggscatter(longdat.cond.both, x = "aucg", y = "p_correct", color = "cond2",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "AUC (Cortisol Stress Response)", ylab = "Percentage of correct responses") + facet_wrap("wm_cap")
wm_plot_2

wm_plot_2 <- ggscatter(longdat.cond.both, x = "aucg", y = "p_winstay", color = "cond2",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "AUC (Cortisol Stress Response)", ylab = "Percentage of correct responses") + facet_wrap("wm_cap")
wm_plot_2

# plots correct performance onto cortisol stress level (aucg) separately in both conditions (2*28 data points)
cond_aucg_plot <- 
  ggplot(longdat.cond.both, aes(aucg,p_correct)) + geom_point() + geom_smooth(aes(group = cond2), method = "lm", se = FALSE) + facet_wrap(~cond2)
cond_aucg_plot

# plots correct performance onto cortisol stress level (zpeak) separately in both conditions (2*28 data points)
cond_peak_plot <- 
  ggplot(longdat.cond.both2, aes(p_correct, z.peak)) + geom_point() + geom_smooth(aes(group = cond2), method = "lm", se = FALSE) + facet_wrap(~cond2)
cond_peak_plot

# plots correct performance onto cortisol stress level in both conditions but one plot (56 data points)
cond_aucg_plot_2 <- ggscatter(longdat.cond.both, x = "aucg", y = "p_correct", color = "cond2",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "AUCG", ylab = "Percentage of correct responses")
cond_aucg_plot_2

# like Otto Fig 4, low and high WM span subjects separate
wm_plot_3 <- ggscatter(longdat.cond.both, x = "aucg", y = "al_win", color = "cond2",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "AUC (Cortisol Stress Response)", ylab = "Alpha Win") + facet_wrap("wm_cap")
wm_plot_3

# plots learning rate onto cortisol stress level in both conditions
model_cort_plot_1 <- ggscatter(longdat.cond.both, x = "al_win", y = "aucg", color = "cond2",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Alpha Win", ylab = "AUCG")
model_cort_plot_1

model_cort_plot_2 <- ggscatter(longdat.cond.both, x = "al_loss", y = "aucg", color = "cond2", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "AUC", ylab = "Alpha Loss")
model_cort_plot_2

model_cort_plot_2 <- ggscatter(longdat.cond.both, x = "kappa", y = "aucg", color = "cond2",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "AUC", ylab = "Kappa")
model_cort_plot_2


```