---
title: "SALAD Analyses in R"
author: "Lara Wieland"
date: "`r format(Sys.time(), '%d %B, %Y')`"
fig_caption: yes
---

# Introduction

This is the analysis of the **main effects of the operant task**. 

## Load packages

```{r}
rm(list = ls()) 

if (!require(ggplot2)) install.packages("ggplot2")
if (!require(ggplot2)) install.packages("readxl")
if (!require(tidyverse)) install.packages("tidyverse")
if (!require(here)) install.packages("here")

library("ggplot2")
library("readxl")
library("tidyverse")
library("here")

```

## Set directory and import data

```{r}

# set path
setwd('/Users/larawieland/Documents/ECN/Promotion/SALAD')

# import data, set missings (999) to NA and turn into tibble
data_imported <- read_delim("operant_prob_summ_wo_excluded.csv", delim = ";",na = c("999", "NA"))
dat <- as.tibble(data_imported)
rm(data_imported)

```
## Subset controls and patients

```{r}
dat.hc <- subset(dat, type == "1")
dat.ad <- subset(dat, type == "2")
```
## Demographics and NP - Descriptive Stats

```{r}

by(dat$age, dat$type, mean)
by(dat$age, dat$type, sd)

by(dat$education, dat$type, mean)
by(dat$education, dat$type, sd)

by(dat$weight, dat$type, mean)
by(dat$weight, dat$type, sd)

by(dat$weight, dat$type, mean)
by(dat$weight, dat$type, sd)

by(dat$weight, dat$type, mean)
by(dat$weight, dat$type, sd)

by(dat$weight, dat$type, mean)
by(dat$weight, dat$type, sd)

```

## Demographics and NP - T-Tests

```{r}
t.test(age ~ type, data=dat)
t.test(education ~ type, data=dat)
t.test(weight ~ type, data=dat)
t.test(IQ_WST ~ type, data=dat)
```

## Two-Way ANOVA
```{r}

# res <- aov(pss ~ marital, data=dat)
# res
# summary(res)

```

## Plots for Descriptive Stats

```{r, fig.width=7, fig.height=5}

plot(dat$p_correct_T1, dat$dsst, xlab="Percentage Correct Operant Task", ylab="DSST", main="Scatterplot of p_correct vs DSST", pch=19, xlim=c(0.5,0.9), ylim=c(50,110), col=ifelse(dat$type == "1", "red", "blue"), cex = 0.5)

```

